[package]
name = "local-fmt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "This crate provides localizable format strings."
authors.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
serde = "1.0"
thiserror = "2.0"
enum-table = "0.1"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde-toml-merge = "0.3"

[lib]
name = "local_fmt"

[lints]
workspace = true

[[example]]
name = "sample"
path = "examples/sample.rs"
